image: node:12

stages:
  - publish

# 更新npm包
npm-publish:
  stage: publish
  only:
    - tags
  script:
    - export GIT_TAG=$(git describe --tags)
    - echo $GIT_TAG
    - npm version $GIT_TAG
    - NPM_TOKEN="$NPM_TOKEN" npm publish