image: node:12

stages:
  - publish

generate:
  stage: publish
  only:
    - master
  script:
    - git config --global user.email "540476284@qq.com"
    - git config --global user.name "KwokRonny"
    - echo "更新版本号"
    - npm version patch
    - git push
    - echo "发布"
    - NPM_TOKEN="$NPM_TOKEN" npm publish 