image: node:12

stages:
  - publish

# 更新npm包
npm-publish:
  stage: publish
  only:
    - master
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}">.npmrc
    - npm publish --access public