image: node:12

stages:
  - publish

# 更新npm包
npm-publish:
  stage: publish
  only:
    - tags
  script:
    - git config --global user.email "540476284@qq.com"
    - git config --global user.name "KwokRonny"
    - export GIT_TAG=$(git describe --tags)
    - echo $GIT_TAG
    - npm version $GIT_TAG
    - NPM_TOKEN="$NPM_TOKEN" npm publish